### ISSUE TITLE
Can't craft with Witchwood or Ghostly items

### ISSUE THREAD

**Issue by UltraGamesYT** [MinecraftModDevelopmentMods/spooky-biomes#7] opened 2019-12-14 17:50 UTC
you said to come and yell at you on github if you hadn't done it already, so here I am. By the way, if you want some custom stick textures I made a couple just cause I was a bit bored.

(also remade the leaves cause they hurt my eyes, i based the spooky leaves off of soul sand and witchwood leaves off of netherrack.)

[https://imgur.com/a/nchelLJ](url)

**Comment by ProxyNeko** [comment] 2019-12-14 18:49
I had honestly forgotten about this so give me a bit more of a reminder as to what you can’t craft and I’ll check if it’s fixed.

The mod should hopefully have an update next week but I’ve renamed some items and blocks and everything has been retextured as well as new content has been added I just need to finish a few small things up and I’ll let you know when it’s out.

**Comment by UltraGamesYT** [comment] 2019-12-14 21:00
Sticks, beds, pressure plates, buttons, tripwire hooks, signs, shields, pistons, noteblocks, jukeboxes, chests, bowls, bookshelves, and boats all aren't compatible with the wood types in this mod. I'd recommend making custom pressure plate, button, and boat textures for Spooky and Witchwood in this mod, and then simply allow for all the other stuff to be compatible with the spooky/witchwood types.

**Comment by ProxyNeko** [comment] 2019-12-14 21:36
Ah I know the cause of that that was fixed in dev a while ago (maybe a year ago I should stop avoiding the tree code) I will look into adding the other three things but the first issue was already fixed just me being slow to finish off and release sorry...

**Comment by UltraGamesYT** [comment] 2019-12-15 17:11
its okay, this is a very neat mod, i'd love to see what you'll do more in the future too! i do some terraria modding and i can understand how sometimes you just hit a wall and dont feel like working.

**Closed** 2019-12-15 17:11 UTC
Labels: Update pending release, enhancement
