### ISSUE TITLE
crash just by traveling the world, or by startup

### ISSUE THREAD

**Issue by Hydraheads** [MinecraftModDevelopmentMods/spooky-biomes#9] opened 2019-12-19 01:34 UTC
https://pastebin.com/jDZwpj5Y

**Comment by ProxyNeko** [comment] 2019-12-19 10:25
I’ll give it a look over later as soon as I can thanks for the report.

**Comment by Sunconure11** [comment] 2019-12-22 17:08
https://paste.dimdev.org/ugiguwoqot.mccrash

Getting a similar crash.

**Comment by ProxyNeko** [comment] 2019-12-22 17:53
I’m onto the cause now just trying to get a fix ready. Thanks for the second log though

**Comment by ProxyNeko** [comment] 2019-12-29 03:10
Fixed in 1.2.0.15 :) Sorry for the wait!

**Closed by ProxyNeko** 2019-12-29 03:10 UTC
Labels: bug
